// This Client ID is from twitchtokengenerator.com and is required to be used with tokens generated by it.
const TWITCH_CLIENT_ID = 'gp762nuuoqcoxypju8c5';
// This is the new redirect URI for the token generator.
const REDIRECT_URI = 'https://twitchtokengenerator.com/';


interface TwitchUser {
  id: string;
  login: string;
  display_name: string;
}

export const getTwitchAuthUrl = (): string => {
  const params = new URLSearchParams({
    client_id: TWITCH_CLIENT_ID,
    redirect_uri: REDIRECT_URI,
    response_type: 'token',
    scope: 'chat:read chat:edit',
  });
  return `https://id.twitch.tv/oauth2/authorize?${params.toString()}`;
};

export const fetchTwitchUser = async (token: string): Promise<TwitchUser | null> => {
  try {
    const response = await fetch('https://api.twitch.tv/helix/users', {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Client-Id': TWITCH_CLIENT_ID,
      },
    });

    if (!response.ok) {
      throw new Error(`Twitch API responded with ${response.status}`);
    }

    const data = await response.json();
    if (data.data && data.data.length > 0) {
      return data.data[0];
    }
    return null;
  } catch (error) {
    console.error("Failed to fetch Twitch user:", error);
    return null;
  }
};